---
database_host: '{{ vault_database_host }}'
database_password: '{{ vault_database_password }}'
database_user: '{{ vault_database_user }}'
symfony_secret: '{{ vault_symfony_secret}}'
loggly_token:  '{{ vault_loggly_token }}'
